// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.accoord.domain;

import java.lang.String;

privileged aspect RoleEntity_Roo_JavaBean {
    
    public String RoleEntity.getName() {
        return this.name;
    }
    
    public void RoleEntity.setName(String name) {
        this.name = name;
    }
    
}
