// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.accoord.domain;

import com.accoord.domain.AssessmentAreaDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect AssessmentAreaIntegrationTest_Roo_IntegrationTest {
    
    declare @type: AssessmentAreaIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: AssessmentAreaIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: AssessmentAreaIntegrationTest: @Transactional;
    
    @Autowired
    private AssessmentAreaDataOnDemand AssessmentAreaIntegrationTest.dod;
    
    @Test
    public void AssessmentAreaIntegrationTest.testCountAssessmentAreas() {
        org.junit.Assert.assertNotNull("Data on demand for 'AssessmentArea' failed to initialize correctly", dod.getRandomAssessmentArea());
        long count = com.accoord.domain.AssessmentArea.countAssessmentAreas();
        org.junit.Assert.assertTrue("Counter for 'AssessmentArea' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void AssessmentAreaIntegrationTest.testFindAssessmentArea() {
        com.accoord.domain.AssessmentArea obj = dod.getRandomAssessmentArea();
        org.junit.Assert.assertNotNull("Data on demand for 'AssessmentArea' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'AssessmentArea' failed to provide an identifier", id);
        obj = com.accoord.domain.AssessmentArea.findAssessmentArea(id);
        org.junit.Assert.assertNotNull("Find method for 'AssessmentArea' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'AssessmentArea' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void AssessmentAreaIntegrationTest.testFindAllAssessmentAreas() {
        org.junit.Assert.assertNotNull("Data on demand for 'AssessmentArea' failed to initialize correctly", dod.getRandomAssessmentArea());
        long count = com.accoord.domain.AssessmentArea.countAssessmentAreas();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'AssessmentArea', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<com.accoord.domain.AssessmentArea> result = com.accoord.domain.AssessmentArea.findAllAssessmentAreas();
        org.junit.Assert.assertNotNull("Find all method for 'AssessmentArea' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'AssessmentArea' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void AssessmentAreaIntegrationTest.testFindAssessmentAreaEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'AssessmentArea' failed to initialize correctly", dod.getRandomAssessmentArea());
        long count = com.accoord.domain.AssessmentArea.countAssessmentAreas();
        if (count > 20) count = 20;
        java.util.List<com.accoord.domain.AssessmentArea> result = com.accoord.domain.AssessmentArea.findAssessmentAreaEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'AssessmentArea' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'AssessmentArea' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void AssessmentAreaIntegrationTest.testFlush() {
        com.accoord.domain.AssessmentArea obj = dod.getRandomAssessmentArea();
        org.junit.Assert.assertNotNull("Data on demand for 'AssessmentArea' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'AssessmentArea' failed to provide an identifier", id);
        obj = com.accoord.domain.AssessmentArea.findAssessmentArea(id);
        org.junit.Assert.assertNotNull("Find method for 'AssessmentArea' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyAssessmentArea(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'AssessmentArea' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AssessmentAreaIntegrationTest.testMerge() {
        com.accoord.domain.AssessmentArea obj = dod.getRandomAssessmentArea();
        org.junit.Assert.assertNotNull("Data on demand for 'AssessmentArea' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'AssessmentArea' failed to provide an identifier", id);
        obj = com.accoord.domain.AssessmentArea.findAssessmentArea(id);
        boolean modified =  dod.modifyAssessmentArea(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        com.accoord.domain.AssessmentArea merged = (com.accoord.domain.AssessmentArea) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'AssessmentArea' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AssessmentAreaIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'AssessmentArea' failed to initialize correctly", dod.getRandomAssessmentArea());
        com.accoord.domain.AssessmentArea obj = dod.getNewTransientAssessmentArea(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'AssessmentArea' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'AssessmentArea' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'AssessmentArea' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void AssessmentAreaIntegrationTest.testRemove() {
        com.accoord.domain.AssessmentArea obj = dod.getRandomAssessmentArea();
        org.junit.Assert.assertNotNull("Data on demand for 'AssessmentArea' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'AssessmentArea' failed to provide an identifier", id);
        obj = com.accoord.domain.AssessmentArea.findAssessmentArea(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'AssessmentArea' with identifier '" + id + "'", com.accoord.domain.AssessmentArea.findAssessmentArea(id));
    }
    
}
